# Project: SIGAC_DB_Sqlite_1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o sqlite/sqlite3.o
LINKOBJ  = main.o sqlite/sqlite3.o
LIBS     = -L"C:/SI-GAC_DB/utils/Dev-Cpp/MinGW64/lib32" -L"C:/SI-GAC_DB/utils/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32
INCS     = -I"C:/SI-GAC_DB/utils/Dev-Cpp/MinGW64/include" -I"C:/SI-GAC_DB/utils/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/SI-GAC_DB/utils/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/SI-GAC_DB/utils/Dev-Cpp/MinGW64/include" -I"C:/SI-GAC_DB/utils/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/SI-GAC_DB/utils/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/SI-GAC_DB/utils/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = SIGAC_DB_Sqlite_1.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

sqlite/sqlite3.o: sqlite/sqlite3.c
	$(CC) -c sqlite/sqlite3.c -o sqlite/sqlite3.o $(CFLAGS)
