#ifndef _UTICOUNTS_UA_1_H_
#  define _UTICOUNTS_UA_1_H_ 

#include "UTICounts.h"

/**
** File UTICounts_UA_1.h
**
** Automatically generated by SCADE Suite UA Adaptor
** Version 6.4.2 (build i25)
**
** Date of generation: 2015-09-18T21:55:12
** Command line:  $ uaadaptor.exe -n 'C:/Program Files (x86)/Esterel Technologies/Esterel SCADE 6.4.2/SCADE/bin/../../SCADE Display/config/Workspace/environments/UAPageCreator/A661Norm/a661.xml' -o 'UTICounts_UA_1' -outdir 'C:/Users/thais/projetosigac/UA/UTICounts/Simulation\' -k 'C:/Users/thais/projetosigac/UA/UTICounts/Simulation/kcg_trace.xml -d 'C:\Users\thais\projetosigac\DF\UTILeitos.sgfx' C:\Users\thais\projetosigac\UA\UTICounts\UTICounts.sdy
**/

/*The default context number if not mapped*/
#ifndef DEFAULT_CONTEXT_NUMBER
#define DEFAULT_CONTEXT_NUMBER 0xDEFA
#endif

/*The input buffer size (bytes) for data from the server*/
#ifndef MAX_SIZE_INPUT_BUFFER
#define MAX_SIZE_INPUT_BUFFER 1000000
#endif

/*The output buffer size (bytes) for data to send to the server*/
#ifndef MAX_SIZE_OUTPUT_BUFFER
#define MAX_SIZE_OUTPUT_BUFFER 1000000
#endif

#ifndef BUFFER_EL
#define BUFFER_EL
typedef unsigned char buffer_el;
#endif

#ifndef EXTERN_OUT_CTX_T
#define extern_out_ctx_t void *
#endif

#ifndef EXTERN_IN_CTX_T
#define extern_in_ctx_t void *
#endif



extern int UTICounts_UA_1_send(buffer_el msg[], outC_UTICounts* scade_ctx,
  extern_out_ctx_t * extern_out_ctx);
extern int UTICounts_UA_1_receive(buffer_el buffer[], int buffer_size,
  inC_UTICounts* scade_ctx, extern_in_ctx_t * extern_in_ctx);
extern void UTICounts_UA_1_receive_clear(inC_UTICounts* scade_ctx,
  extern_in_ctx_t * extern_in_ctx);


#endif /* _UTICOUNTS_UA_1_H_ */
